config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :task_categories
  resources :task_logs
 
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  
  root to: "home#index"
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :restrict_with_error
  
  validates_presence_of :name
  
  def to_s
    self.name
  end
end

app/controllers/task_categories_controller.rb
class TaskCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_task_category, only: [:show, :edit, :update, :destroy]

  # GET /task_categories
  # GET /task_categories.json
  def index
    @task_categories = @user.task_categories
  end

  # GET /task_categories/1
  # GET /task_categories/1.json
  def show
  end

  # GET /task_categories/new
  def new
    @task_category = TaskCategory.new
  end

  # GET /task_categories/1/edit
  def edit
  end

  # POST /task_categories
  # POST /task_categories.json
  def create
    @task_category = TaskCategory.new(task_category_params)
    @task_category.user = @user

    respond_to do |format|
      if @task_category.save
        format.html { redirect_to @task_category, notice: 'Task category was successfully created.' }
        format.json { render :show, status: :created, location: @task_category }
      else
        format.html { render :new }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_categories/1
  # PATCH/PUT /task_categories/1.json
  def update
    respond_to do |format|
      if @task_category.update(task_category_params)
        format.html { redirect_to @task_category, notice: 'Task category was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_category }
      else
        format.html { render :edit }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_categories/1
  # DELETE /task_categories/1.json
  def destroy
    respond_to do |format|
      if @task_category.destroy
        format.html { redirect_to task_categories_url, notice: 'Task category was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to task_categories_url, alert: 'Task category was not successfully destroyed. Error message: ' + @task_category.errors.full_messages.first }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_category
      @task_category = TaskCategory.where(id: params[:id], user: @user).take!
    end
    
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_category_params
      params.require(:task_category).permit(:name, :reference_url)
    end
end

app/views/task_categories/_form.html.erb
<%= simple_form_for(@task_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :reference_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/task_categories/edit.html.erb
<h1 class="page-header">Editing Task Category</h1>

<%= render 'form', task_category: @task_category %>

<%= link_to 'Show', @task_category %> |
<%= link_to 'Back', task_categories_path %>

app/views/task_categories/index.html.erb
<h1 class="page-header">Task Categories</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Reference url</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @task_categories.each do |task_category| %>
      <tr>
        <td><%= task_category.name %></td>
        <td><%= task_category.reference_url %></td>
        <td class="actions-td">
          <%= link_to 'Show', task_category, class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_task_category_path(task_category), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', task_category, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Category', new_task_category_path, class: 'btn btn-primary' %>

app/views/task_categories/new.html.erb
<h1>New Task Category</h1>

<%= render 'form', task_category: @task_category %>

<%= link_to 'Back', task_categories_path %>

app/views/task_categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task_category.name %>
</p>

<p>
  <strong>Reference url:</strong>
  <%= @task_category.reference_url %>
</p>

<%= link_to 'Edit', edit_task_category_path(@task_category) %> |
<%= link_to 'Back', task_categories_path %>