config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :task_categories
  resources :task_logs
 
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  
  root to: "home#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_category
  belongs_to :user
  has_many :task_logs, dependent: :restrict_with_error
  
  validates_presence_of :name
  
  def to_s
    return "#{self.name} - #{self.description}" if self.description.present?
    return self.name
  end
  
  def category_reference_url
    sanitized_name = ActionController::Base.helpers.sanitize self.name
    return task_category.reference_url.sub("{task_name}", sanitized_name) if self.task_category.reference_url.present?
    return nil
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = @user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    respond_to do |format|
      if @task.destroy
        format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to tasks_url, alert: 'Task was not successfully destroyed. Error message: ' + @task.errors.full_messages.first }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.where(id: params[:id], user: @user).take!
    end

    def set_user
      @user = current_user
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :task_category_id)
    end
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :task_category %>
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="page-header">Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1 class="page-header">Tasks</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Task category</th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.task_category, task_category_path(task.task_category) %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td class="actions-td">
          <%= link_to 'Show', task, class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', task, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>

app/views/tasks/new.html.erb
<h1 class="page-header">New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Task category:</strong>
  <%= @task.task_category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>