config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :task_categories
  resources :task_logs
 
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  
  root to: "home#index"
end

app/models/task_log.rb
class TaskLog < ApplicationRecord
  belongs_to :user
  belongs_to :task, optional: true
  
  validates_presence_of :date
  
  def url
    self.task.category_reference_url if task.present?
  end
end

app/controllers/task_logs_controller.rb
class TaskLogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_task_log, only: [:show, :edit, :update, :destroy]

  # GET /task_log
  # GET /task_log.json
  def index
    @today_tasks = @user.task_logs.where(date: Date.current).order(date: :desc)
    if params[:show_tasks] == 'today'
      @task_logs = @today_tasks
    else
      @task_logs = @user.task_logs.order(date: :desc)
    end
    
    @today_tasks_time = get_today_tasks_time @today_tasks
  end

  # GET /task_log/1
  # GET /task_log/1.json
  def show
  end

  # GET /task_log/new
  def new
    @tasks = Task.order(:name)
    @task_log = TaskLog.new
    @task_log.date = Date.current
  end

  # GET /task_log/1/edit
  def edit
    @tasks = Task.order(:name)
  end

  # POST /task_log
  # POST /task_log.json
  def create
    @task_log = TaskLog.new(task_log_params)
    @task_log.user = @user

    respond_to do |format|
      if @task_log.save
        format.html { redirect_to task_log_path(@task_log), notice: 'Task log was successfully created.' }
        format.json { render :show, status: :created, location: @task_log }
      else
        format.html { render :new }
        format.json { render json: @task_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_log/1
  # PATCH/PUT /task_log/1.json
  def update
    respond_to do |format|
      if @task_log.update(task_log_params)
        format.html { redirect_to task_log_path, notice: 'Task log was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_log }
      else
        format.html { render :edit }
        format.json { render json: @task_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_log/1
  # DELETE /task_log/1.json
  def destroy
    @task_log.destroy
    respond_to do |format|
      format.html { redirect_to task_logs_url, notice: 'Task log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_log
      @task_log = TaskLog.where(id: params[:id], user: @user).take!
    end
    
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_log_params
      params.require(:task_log).permit(:name, :duration, :date, :description, :task_id)
    end
    
    def get_today_tasks_time tasks
      time = 0
      tasks.each do |task|
        time += task.duration if task.duration.present?
      end
      return time
    end
end

app/views/task_logs/_form.html.erb
<%= simple_form_for(@task_log) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :task, label_method: :to_s, collection: @tasks %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :duration %>
    <%= f.input :date, html5: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/task_logs/edit.html.erb
<h1 class="page-header">Editing Task Log</h1>

<%= render 'form', task_log: @task_log %>

<%= link_to 'Show', @task_log %> |
<%= link_to 'Back', task_logs_path %>

app/views/task_logs/index.html.erb
<h1 class="page-header">Task Logs</h1>
<%= link_to "Today only", :show_tasks => "today" %> | 
<%= link_to "All", :show_tasks => "all" %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Task</th>
      <th>Name</th>
      <th>Description</th>
      <th>Duration</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @task_logs.each do |task_log| %>
      <tr>
        <td><%= link_to truncate(task_log.task.to_s, length: 58), task_log.url, target: '_blank' %></td>
        <td><%= task_log.name %></td>
        <%= content_tag(:td, truncate(task_log.description, length: 8), title: task_log.description) %>
        <td><%= task_log.duration %></td>
        <td><%= l task_log.date  %></td>
        <td class="actions-td">
          <%= link_to 'Show', task_log, class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_task_log_path(task_log), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', task_log, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Daily Task', new_task_log_path, class: 'btn btn-primary' %>
<br />
<br />
Today you did <%= @today_tasks_time %> hour(s).

app/views/task_logs/new.html.erb
<h1 class="page-header">New Task Log</h1>

<%= render 'form', task_log: @task_log %>

<%= link_to 'Back', task_logs_path %>

app/views/task_logs/show.html.erb
<p>
  <strong>Task:</strong>
  <%= @task_log.task %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task_log.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_log.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task_log.duration %>
</p>

<p>
  <strong>Date:</strong>
  <%= l @task_log.date %>
</p>

<%= link_to 'Edit', edit_task_log_path(@task_log) %> |
<%= link_to 'Back', task_logs_path %>